services:
  providers:
    build:
      context: .
    volumes:
      - .:/opt/project
    environment:
      - MONGODB_URL
      - REDIS_URL
      - ADMIN_DB_URL
      - GOOGLE_API_KEY
      - WINDLINE_SQL_URL
      - CHECKWX_API_KEY
      - ROMMA_KEY
      - IWEATHAR_KEY
      - BORN_TO_FLY_VENDOR_ID
      - BORN_TO_FLY_DEVICE_ID
      - WINDY_API_KEY
      - PROVIDER
      - KACHELMANN_API_KEY
networks:
  default:
    name: winds-mobi
